name: Release and Dispatch
run-name: Release ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - '*'
      - '!*alpha*'
      - '!*beta*'

permissions:
  contents: write
  actions: write

jobs:
  release:
    uses: ianhubnet/.github/.github/workflows/project.yml@main
    with:
      name: ${{ vars.CSK_NAME }}
    secrets: inherit
